language: cpp
compiler:
  - gcc
  - clang
os:
  - osx
  - linux
env:
  - PLATFORM=Win32
  - PLATFORM=Win64
  - PLATFORM=Unix
before_install: ./util/travis/before_install.sh
script: ./util/travis/script.sh
sudo: required
notifications:
  email: false
matrix:
  fast_finish: true
  exclude:
    - env: PLATFORM=Win32
      compiler: clang
    - env: PLATFORM=Win64
      compiler: clang
    - env: PLATFORM=Win32
      os: osx
    - env: PLATFORM=Win64
      os: osx
    - compiler: gcc
      os: osx
